export const LINKEDIN_PROFILE: string = 'https://www.linkedin.com/in/tomerchermesh'
export const GITHUB_PROFILE: string = 'https://github.com/TomerChermesh'
export const CV_FILE_PATH: string = '/TomerChermeshCV.pdf'
export const PROJECT_FPL_MLI: string = 'https://fpl.tomerchermesh.com'
export const PROJECT_STADIUMAP: string = 'https://stadiumap.tomerchermesh.com/'